export const coursesData = [
  {
    title: 'AI Engineer Bootcamp',
    desc: 'Ruta certificada de 6 semanas. Domina LLMs, RAG, sistemas multiagente con CrewAI y LangGraph, y despliega en producción.',
    logoText: 'AIE',
    logoBg: 'rgba(79,70,229,0.20)',
    logoColor: '#818CF8',
    tag: 'Bootcamp',
    tagColor: '#4F46E5',
    detailPath: '/cursos/ai-engineer',
  },
  {
    title: 'Mastering Claude',
    desc: 'Domina el ecosistema Claude: prototipa con Anthropic Labs, programa con Claude Code CLI y despliega agentes empresariales con MCP.',
    logoText: 'MC',
    logoBg: 'rgba(217,119,6,0.20)',
    logoColor: '#FCD34D',
    tag: 'IA Generativa',
    tagColor: '#D97706',
    detailPath: '/cursos/mastering-claude',
  },
  {
    title: 'Agentes con LangFlow',
    desc: 'Crea agentes inteligentes con flujos visuales, memoria y APIs. Listos para producción.',
    logoText: 'LF',
    logoBg: 'rgba(37,99,235,0.20)',
    logoColor: '#60A5FA',
    tag: 'IA Generativa',
    tagColor: '#2563EB',
    detailPath: '/cursos/langflow',
  },
]
